### ISSUE TITLE
Feature: documentation

### ISSUE THREAD

**Issue by dbkaplun** [dpapathanasiou/go-recaptcha#10]
Hello,

It would be great if go-recaptcha had godocs that showed the available structs and options. Some documentation would help determine what types to use, for instance.

Thanks for considering!

**Comment by matthewhartstonge** [comment]
https://godoc.org/github.com/dpapathanasiou/go-recaptcha 😉 

You can plug any repo into `godoc.org` and it will generate docs for you.

**Comment by dpapathanasiou** [comment]
@matthewhartstonge Thanks!
