### ISSUE TITLE
ErrorCodes are now a list of strings

### ISSUE THREAD

**Issue by nicluo** [dpapathanasiou/go-recaptcha#6]
Was trying out this recaptcha library but got into some errors that needed troubleshooting.

    Read error: got invalid JSON: json: cannot unmarshal string into Go struct field 
    RecaptchaResponse.error-codes of type int

According to reCAPTCHA documentation on [Verifying the user's response](https://developers.google.com/recaptcha/docs/verify), `error-codes` are now a list of strings.

Changing RecaptchaResponse should avoid the error.

    type RecaptchaResponse struct {
    	Success     bool      `json:"success"`
    	ChallengeTS time.Time `json:"challenge_ts"`
    	Hostname    string    `json:"hostname"`
    	ErrorCodes  []string  `json:"error-codes"`
    }

Thought this information might be helpful :)

**Comment by dataflowjs** [comment]
Yah! too, helped...
